### ISSUE TITLE
async_forward_entry_setup deprecated

### ISSUE THREAD

**Issue by cpettis** [rewardone/homeassistant-culligan-water-softener#10]
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:188
First occurred: 11:26:55 AM (2 occurrences)
Last logged: 11:26:58 AM

Detected that custom integration 'culligan' calls async_forward_entry_setup for integration, culligan with title: Culligan - and entry_id: 5741210006cdfedfa7893de64904c8aa, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/culligan/__init__.py, line 160: await hass.config_entries.async_forward_entry_setup(config_entry, platform), please create a bug report at https://github.com/rewardone/homeassistant-culligan-water-softener/issues

**Comment by rewardone** [comment]
@cpettis please update the integration to 1.3.3. When tested on my instance, adding await stopped the error from reappearing. 

[1.3.3](https://github.com/rewardone/homeassistant-culligan-water-softener/releases/tag/v1.3.3)

**Comment by rewardone** [comment]
Appreciate the report cpettis, [1.3.4](https://github.com/rewardone/homeassistant-culligan-water-softener/commit/59a1acc6552be3769739a3cd48d2c2b9d132fae1) should fix. HACS should push it out on the next refresh.

I'll close this for now, but we can re-open if it reappears.
