### ISSUE TITLE
Something unknown happened.

### ISSUE THREAD

**Issue by loictinant** [rewardone/homeassistant-culligan-water-softener#11]
Hello,

I can’t connect, I get a “Something unknown happened” error.

What should I do?

![Capture d’écran 2024-11-14 190927](https://github.com/user-attachments/assets/a1863bb0-913e-4cc6-bd97-f0e3880c0495)

**Comment by rewardone** [comment]
Ultimately I'm not sure how Culligan devices interact. I don't know if they are regional or not. I added a region selector because the underlying Ayla API has different endpoints for certain EU devices. 

You can try: 

- Setting region to Elsewhere
- Enable debug logging and uploading here

Currently, the [sign in code](https://github.com/rewardone/homeassistant-culligan-water-softener/blob/main/custom_components/culligan/config_flow.py#L93-L94) doesn't [pass](https://github.com/rewardone/Culligan/blob/main/src/culligan/uniapi_culliganiot.py#L266) the EU bool to [Ayla](https://github.com/rewardone/ayla-iot-unofficial/blob/main/src/ayla_iot_unofficial/ayla_iot_unofficial.py#L50).

**Comment by loictinant** [comment]
It doesn't change anything by activating EU or other.
And how to activate the journal since I can't activate it?

**Comment by loictinant** [comment]
Enregistreur: custom_components.culligan
Source: custom_components/culligan/config_flow.py:94
intégration: Culligan ([documentation](https://github.com/rewardone/homeassistant-culligan-water-softener), [problèmes](https://github.com/rewardone/homeassistant-culligan-water-softener/issues))
S'est produit pour la première fois: 12:10:26 (2 occurrences)
Dernier enregistrement: 12:10:39

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/culligan/config_flow.py", line 94, in validate_input
    await culligan.async_sign_in()
  File "/usr/local/lib/python3.12/site-packages/culligan/uniapi_culliganiot.py", line 158, in async_sign_in
    self._set_credentials(resp.status, await resp.json())
  File "/usr/local/lib/python3.12/site-packages/culligan/uniapi_culliganiot.py", line 120, in _set_credentials
    self._ayla_access_token     = login_result["data"]["linkedAccounts"]["ayla"]["access_token"]
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'ayla'

**Comment by rewardone** [comment]
You can try  [v1.3.5-beta1](https://github.com/rewardone/homeassistant-culligan-water-softener/releases/tag/v1.3.5-beta1) and see what debug/error messages are different.

**Comment by rewardone** [comment]
There is a [regex](https://github.com/rewardone/homeassistant-culligan-water-softener/blob/main/custom_components/culligan/config_flow.py#L69) that is supposed to capture most valid email addresses. You can test to see if this regex is not validating your email and let me know what is missing.

**Comment by loictinant** [comment]
sorry I didn't understand what to do (I'm French)

**Comment by loictinant** [comment]
I recreated an account with a Gmail email address (before it was Hotmail), and I managed to connect.

Now the integration finds nothing.

Enregistreur: homeassistant.config_entries
Source: config_entries.py:635
S'est produit pour la première fois: 23:05:40 (1 occurrences)
Dernier enregistrement: 23:05:40

Error setting up entry Culligan - for culligan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/culligan/__init__.py", line 111, in async_setup_entry
    if len(culliganiot_devices) > 0 and len(culligan_devices) > 0:
                                            ^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'culligan_devices' where it is not associated with a value

**Comment by loictinant** [comment]
So what I just saw is weird.

My new one already doesn't work anymore and the old one works. In fact, as soon as I add my softener to the app, I can't connect to the integration anymore.

**Comment by rewardone** [comment]
You can try [beta2](https://github.com/rewardone/homeassistant-culligan-water-softener/releases/tag/v1.3.5-beta2). I tried to add additional logic to the device array selection [code](https://github.com/rewardone/homeassistant-culligan-water-softener/blob/v1.3.5-beta2/custom_components/culligan/__init__.py#L111)

**Comment by loictinant** [comment]
Beta2

Enregistreur: homeassistant.config_entries
Source: config_entries.py:635
S'est produit pour la première fois: 15:35:33 (1 occurrences)
Dernier enregistrement: 15:35:33

Error setting up entry Culligan - for culligan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/culligan/__init__.py", line 111, in async_setup_entry
    if culliganiot_devices and culligan_devices:
                               ^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'culligan_devices' where it is not associated with a value

**Comment by rewardone** [comment]
Gotcha, so something is happening when the integration queries for devices ... and the checks aren't working as expected. 

If you have debug logging enabled, there should be a few lines of logs regarding: [x num of devices, etc.](https://github.com/rewardone/homeassistant-culligan-water-softener/blob/v1.3.5-beta2/custom_components/culligan/__init__.py#L93). Do you have any of those debug logs?

**Comment by loictinant** [comment]
Where can I find these newspapers?

**Comment by rewardone** [comment]
A great point. If you have VS Code plugin or another way to edit code, you can modify this integration's [supported classes](https://github.com/rewardone/homeassistant-culligan-water-softener/blob/main/custom_components/culligan/__init__.py#L133) and [include the class from the library](https://github.com/rewardone/homeassistant-culligan-water-softener/blob/main/custom_components/culligan/__init__.py#L17). It doesn't include the generic [CulliganIoTDevice](https://github.com/rewardone/Culligan/blob/8bb06c2af7e22fbf9ad9d04bf77c36a520e6df60/src/culligan/uniapi_culliganiot.py#L353C32-L353C49), which it the device would possible be cast to.

If you can confirm that Smart Modernity is your device["name"], I'll get those changes added and we can test them.

**Comment by rewardone** [comment]
I released [beta3](https://github.com/rewardone/homeassistant-culligan-water-softener/releases/tag/v1.3.5-beta3), which bumps the version for the Culligan library which now includes Smart Modernity. Fingers crossed for some progress :)

**Comment by rewardone** [comment]
And thank you for the support in developing a fix! 
[1.3.5](https://github.com/rewardone/homeassistant-culligan-water-softener/releases/tag/v1.3.5) released

**Comment by t3rral33t** [comment]
> Pushed [beta4](https://github.com/rewardone/homeassistant-culligan-water-softener/releases/tag/v1.3.5-beta4). I bumped Culligan again to add the _dsn property to the class. Someone is using Smart HE and didn't report the issues, so I'm cautious of breaking things. This should allow the existing join(_dsn) code to work.
> 
> Indented the button and switch to be within their respective loops.
> 
> Initialized the culligan_devices array.

I'm using a Smart HE and I have no devices or entities.  I'm trying my best to follow along here but do you need some information about this hardware?  I would be happy to provide.
