### ISSUE TITLE
System device support request - uniapi.culliganiot.com

### ISSUE THREAD

**Issue by cpettis** [rewardone/homeassistant-culligan-water-softener#3]
Using the most recent release, I am still getting the error shown below using home assistant 2023.10.1

Logger: homeassistant.helpers.integration_platform
Source: helpers/integration_platform.py:50
First occurred: 11:30:20 AM (8 occurrences)
Last logged: 11:34:48 AM

Unexpected error importing culligan/system_health.py
Unexpected error importing culligan/logbook.py
Unexpected error importing culligan/media_source.py
Unexpected error importing culligan/silabs_multiprotocol.py
Unexpected error importing culligan/hardware.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 50, in _async_process_single_integration_platform_component
    platform = integration.get_platform(platform_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 838, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 855, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.culligan_water_softener.diagnostics'

**Comment by rewardone** [comment]
I am also on 2023.10.1. My production instance is using HASS OS and development instance is running on top of Debian. 

As you can see in the code, none of those files exist. 
What are the steps you use to generate these errors? 

HACs should download this into custom_components/culligan. 
Try to reboot your entire instance and then configure the integration.

**Comment by rewardone** [comment]
I will further clarify that you should delete any other culligan* folders within custom_components and then restart Home Assistant. 

HACs will download the structure and place it into a folder by its domain name, which is culligan. 
The domain name is NOT culligan_water_softener like the repository name may suggest, and it can be viewed in both the directory structure and src/const.py. 

The integration, likewise, will simply have the domain name, culligan, when you go to add it to your instance.

**Comment by cpettis** [comment]
That removed the errors, but my system does not show up. 
2023-10-10 13:56:15.282 DEBUG (MainThread) [custom_components.culligan] options {}
2023-10-10 13:56:15.282 DEBUG (MainThread) [custom_components.culligan] unique_id
2023-10-10 13:56:15.282 DEBUG (MainThread) [custom_components.culligan] source user
2023-10-10 13:56:15.283 DEBUG (MainThread) [custom_components.culligan] Instance was not given ... creating one
2023-10-10 13:56:15.283 DEBUG (MainThread) [custom_components.culligan] async_connect_or_timeout
2023-10-10 13:56:15.283 DEBUG (MainThread) [custom_components.culligan] Initialize connection to Ayla networks API
2023-10-10 13:56:16.382 DEBUG (MainThread) [custom_components.culligan] Asking for devices
2023-10-10 13:56:16.487 DEBUG (MainThread) [custom_components.culligan] Found 0 Culligan device(s): 
Is there something I need to do on the website for the integration to be able to see my system? Or did I miss something when I configured the integration?

**Comment by rewardone** [comment]
What softener do you have? 
Is it connected to the internet? 
Are your culligan application credentials correct? (email and password)

Those errors indicate that your device is not being returned by the backend service: Ayla Networks. 

The best way to debug from here would be to provide proxy traffic (removing any sensitive data). 
You can also go through the steps manually in a python interpreter to identify where you are receiving the error. 

in a new python virtual environment (venv) 
pip install ayla_iot_unofficial
pip install culligan 

in an interpreter, something like the [culligan ](https://github.com/rewardone/Culligan)packages README: 
`import culligan
USERNAME = 'me@email.com'
PASSWORD = '$7r0nkP@s$w0rD'

CulliganApi = new_culligan_api(username, password)

device_list = CulliganApi.Ayla.list_devices()
print(device_list)

devices = CulliganApi.Ayla.get_devices())
print(devices)`

**Comment by cpettis** [comment]
It is a Smart HE model. It is connected to the internet, I can control it from the app on my phone without being connected to the wifi in my house. Using the code below:
`CulliganApi.Ayla = CulliganApi.get_ayla_api()
print(CulliganApi.Ayla._login_data)

device_list = CulliganApi.Ayla.list_devices()
print(device_list)

devices = CulliganApi.Ayla.get_devices()
print(devices)`
I got the output below from the print statements:
{'user': {'email': 'cpettis1980@yahoo.com', 'password':removed, 'application': {'app_id': 'OAhRjZjfBSwKLV8MTCjscAdoyJKzjxQW', 'app_secret': None}}}
[]
[]

**Comment by rewardone** [comment]
The sign_in method let's data be returned, we can check it for 'linkedAccounts'. 

You can try:
```
print(CulliganApi.sign_in(True))
print(CulliganApi._is_authed)`
print(CulliganApi._ayla_access_token)
```

the sign_in should return a userId, accessToken, refreshToken, and linkedAccounts { }
the linkedAccounts contains ayla : { access_token, refresh_token, etc}

Maybe your log in is not working or somehow your device and account are not linked to Ayla. Without the Ayla access token, device data is extremely limited until culligan expands their uniapi.culliganiot.com/api, which is just a limited wrapper in front of Ayla (and no documentation). 

To see if you are getting an access token from Ayla. I am aware of the potential for regional differences. Are you and the device in North America?

**Comment by cpettis** [comment]
The system is in the US.

{'success': True, 'data': {'userId': 'NuSmDOF7djeHY48LGBfBzaJQPX8W2gvf', 'accessToken': 'eyJhbGciOiJSUzI1NiIsImtpZCI6ImYyZTgyNzMyYjk3MWExMzVjZjE0MTZlOGI0NmRhZTA0ZDgwODk0ZTciLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vY2d3LWlvdHVuaWZpZWRhcGktcHJvZCIsImF1ZCI6ImNndy1pb3R1bmlmaWVkYXBpLXByb2QiLCJhdXRoX3RpbWUiOjE2OTY5ODE4NDgsInVzZXJfaWQiOiJvRnd5M0lwbkh4YUNVVFRzUW5YWURNMk9oZEgyIiwic3ViIjoib0Z3eTNJcG5IeGFDVVRUc1FuWFlETTJPaGRIMiIsImlhdCI6MTY5Njk4MTg0OCwiZXhwIjoxNjk2OTg1NDQ4LCJlbWFpbCI6ImNwZXR0aXMxOTgwQHlhaG9vLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJjcGV0dGlzMTk4MEB5YWhvby5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.XAfuMfuZ1MNxrlF4q2a2OxGu7wh64tcR5WHecvvya2CR_sY9aEj6zUqdQ3b01WssYuawhWAybV_LQ6WQ7-iyfaEKb9tojBjr53TKAWP5PzHMM0yAT4CH1NWQtoIe4lSW9e2AtUY5HB0CuUCDX8b16OA44fepy_03rNNIZSQ_oyUdcLEcitlKjAVicgk-P0x0AHxtJ6ZiC2jQh8Bif6AUQZYQhJq22Oonbsisv21kgtaSqdEqS3-rTjvvj-7Yzr7MDGtMuhv6_RfubSS8_UnSKy5qV9OqFR2KN2w4GvmP1OsPQFIsy8OXrcJd_s1zzO7EAYZti2WAn639Mi3PwF1T8Q', 'refreshToken': 'AMf-vBzIZdzIL4wFrROWQ2rJviLGByNW8zvZ4RmVCTLKeG5NyWoha4U8JJFWDPMSDoBNSvemn_QqDU5kxU7p7s0OHkHMjC5V6svJJtR_jI0xN3Y-Ogr_dcV6lTUeCBT_VzMOD4oJ7DwWz7iJlsIY2g8y0p3mJPCyiVZ6JMq0lZvhM7Rcr7GmPIGQh8LWvd-Y7fmraIHAX6tOxW7X8Rj2ccy247nGBbDA-2Yo1FRpq2XWUgRqmZqCZHA', 'expiresIn': 3600, 'linkedAccounts': {'ayla': {'access_token': '3146c83fd3914d20ae9ef17bee00d73b', 'refresh_token': 'f6817e4ef6914ed8ba4e21618e9cd2ed', 'expires_in': 86400, 'role': 'EndUser', 'role_tags': [], 'code': 'ok'}}, 'roles': ['user']}}
True
3146c83fd3914d20ae9ef17bee00d73b

**Comment by rewardone** [comment]
Very odd indeed. The user_profile is an email @ayla.int.sso.culliganiot.com. 

When you did set up this unit? My thought is that older devices still have the ability to connect to ayla directly, but newer devices are now onboarded directly to culliganiot.com.

**Comment by rewardone** [comment]
Example, my instance returns no data at uniapi.culliganiot.com/api/v1/device/registry and does return data from ayla/devices.json

Your enrollment is the exact opposite. Returning data with /device/registry and returning no data from ayla/devices.json. 

Your serial number (starting with GB and ending with I6), which should be your DSN, also does not retrieve any data when used with Ayla directly, which is how the integration currently functions. 

Unfortunately without some proxy data or documentation to see what endpoints are available and how the app is now communicating with culliganiot, I will be unable to assist. :(

**Comment by cpettis** [comment]
The unit was setup last week. Thanks for trying to help me out.

**Comment by rewardone** [comment]
If you want, you can set up BurpSuite Community or Fiddler with your mobile device and start intercepting traffic. Find the endpoints and what is needed. Data similar to the spreadsheet in the Culligan discovery repository.

Alternatively, if you want to trust a stranger, we can figure out a way to share login credentials so I can proxy the traffic. 

I did submit an email to Culligan through their website asking about API documentation, but I'm not hopeful on that route.

**Comment by cpettis** [comment]
I think these are the endpoints you were looking for.
GET https://uniapi.culliganiot.com/api/v1/device/data?serialNumber=GBX2...
GET https://uniapi.culliganiot.com/api/v1/device/state?serialNumber=GBX2...
GET https://uniapi.culliganiot.com/api/v1/device/registry
GET https://uniapi.culliganiot.com/api/v1/notifications
POST https://uniapi.culliganiot.com/api/v1/device/command
  {"command":"telemetry.get","serialNumber":"GBX2-...","protocolVersion":1,"params":{},"requestId":"CC-2023-10-11T16:31:03.458-..."}
{"command":"awayMode.set","serialNumber":"GBX2-...","protocolVersion":1,"params":{"active":1},"requestId":"CC-2023-10-11T16:31:03.077-..."}

I don't know enough about how the post function works to figure out how to generate the requestId, but I was able to get all the device get commands to work.
I still have 10 days left on my trial of fiddler if you want me to try something else.

**Comment by cpettis** [comment]
I finally did get the post command working, and could verify that I could turn on and off away mode. I couldn't verify that I was turning on and off bypass mode from any of the data I saw.
I was able to capture the bypass commands also:
{
	"params": {
		"duration": 60
	},
	"serialNumber": "GBX2-...",
	"protocolVersion": 1,
	"requestId": "CC-2023-10-11T21:41:25.250-...",
	"command": "bypass.timed.on"
}

"command": "bypass.off"
"command": "bypass.permanent.on"

**Comment by rewardone** [comment]
Yes, this is the type of data I'll need. 

for each of these, I'll need any data in the requests (likely there is only body data in the POST requests)

GET https://uniapi.culliganiot.com/api/v1/device/data?serialNumber=<serial>
GET https://uniapi.culliganiot.com/api/v1/device/state?serialNumber=<serial>
GET https://uniapi.culliganiot.com/api/v1/device/registry
GET https://uniapi.culliganiot.com/api/v1/notifications
POST https://uniapi.culliganiot.com/api/v1/device/command

and I'll also need the full response so I can see what object is needed to be parsed (usually some JSON response, but I'll need to get the keys correct). 

In the Culligan spreadsheet, you can see that Ayla is providing like 50 properties (not an exact number but it's a lot). I'll only be able to build sensors for the data being returned from culliganiot.

I'll definitely dig into the commands later. Those will need to be implemented as services of some kind and I don't know how to do that yet. Good to capture the data now though. 

I really hope I don't have to match up getting data requests from specific request Ids ...

**Comment by cpettis** [comment]
I have 2 sessions recorded from Fiddler, but I haven't figured out a way to export them. 
[device_data2.json](https://github.com/rewardone/homeassistant-culligan-water-softener/files/12886047/device_data2.json)
The device state and registry .json files have the serial number, so I'm not sure if I want to post them.

**Comment by rewardone** [comment]
you can edit the json files in your favorite text editor and remove anything you'd like. 

the device_data2 is really great data. it looks much simpler than the property data returned from Ayla.

**Comment by cpettis** [comment]
Cleaned out anything I didn't want to post.
I also posted an example of the post I used for /device/command. I used the CulliganApi.self_request and included examples of the json parameters I used for each funcntion I was able to identify with fiddler

[device_registry_clean.json](https://github.com/rewardone/homeassistant-culligan-water-softener/files/12886416/device_registry_clean.json)
[device_state_clean.json](https://github.com/rewardone/homeassistant-culligan-water-softener/files/12886417/device_state_clean.json)
[Post Request Example.txt](https://github.com/rewardone/homeassistant-culligan-water-softener/files/12886420/Post.Request.Example.txt)

**Comment by rewardone** [comment]
And now the trial and error begins. Please update your integration to the latest beta release. It should be select-able in HACs if you enable beta releases. v1.0.2-beta.3

At the very least, I expect this to recognize that there is a culligan iot device and register that it is online. 

In my instance, where only ayla devices exist, the integration is working without errors.

If you'd like to troubleshoot or step through anything on your end, please update the culligan package to the latest release.

**Comment by cpettis** [comment]
Here are the error messages I got with this version. 

2023-10-13 13:04:35.596 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration culligan: Unable to import component: cannot import name 'CulliganApi' from 'culligan.exc' (/usr/local/lib/python3.11/site-packages/culligan/exc.py)
File "/config/custom_components/culligan/__init__.py", line 10, in <module>
from .update_coordinator import CulliganUpdateCoordinator
File "/config/custom_components/culligan/update_coordinator.py", line 10, in <module>
from culligan.exc import CulliganApi, CulliganAuthError, CulliganNotAuthedError, CulliganAuthExpiringError
ImportError: cannot import name 'CulliganApi' from 'culligan.exc' (/usr/local/lib/python3.11/site-packages/culligan/exc.py)
File "/config/custom_components/culligan/__init__.py", line 10, in <module>
from .update_coordinator import CulliganUpdateCoordinator
File "/config/custom_components/culligan/update_coordinator.py", line 10, in <module>
from culligan.exc import CulliganApi, CulliganAuthError, CulliganNotAuthedError, CulliganAuthExpiringError
ImportError: cannot import name 'CulliganApi' from 'culligan.exc' (/usr/local/lib/python3.11/site-packages/culligan/exc.py)
File "/config/custom_components/culligan/__init__.py", line 10, in <module>
from .update_coordinator import CulliganUpdateCoordinator
File "/config/custom_components/culligan/update_coordinator.py", line 10, in <module>
from culligan.exc import CulliganApi, CulliganAuthError, CulliganNotAuthedError, CulliganAuthExpiringError
ImportError: cannot import name 'CulliganApi' from 'culligan.exc' (/usr/local/lib/python3.11/site-packages/culligan/exc.py)
2023-10-13 13:05:54.271 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration culligan: cannot import name 'CulliganApi' from 'culligan.exc' (/usr/local/lib/python3.11/site-packages/culligan/exc.py)
File "/config/custom_components/culligan/__init__.py", line 10, in <module>
from .update_coordinator import CulliganUpdateCoordinator
File "/config/custom_components/culligan/update_coordinator.py", line 10, in <module>
from culligan.exc import CulliganApi, CulliganAuthError, CulliganNotAuthedError, CulliganAuthExpiringError
ImportError: cannot import name 'CulliganApi' from 'culligan.exc' (/usr/local/lib/python3.11/site-packages/culligan/exc.py)

Logger: homeassistant.config_entries
Source: config_entries.py:2069
First occurred: 1:24:26 PM (1 occurrences)
Last logged: 1:24:26 PM

Error occurred loading flow for integration culligan: cannot import name 'CulliganApi' from 'culligan.exc' 
(/usr/local/lib/python3.11/site-packages/culligan/exc.py)

**Comment by cpettis** [comment]
After I fixed the import error in upadate_coordinator.py (CulliganApo is not in .exc.py) I now get the error shown below:
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:359
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 2:20:09 PM (2 occurrences)
Last logged: 2:20:54 PM
Error while setting up culligan platform for sensor

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/culligan/sensor.py", line 279, in async_setup_entry
    SoftenerSensor(
  File "/config/custom_components/culligan/sensor.py", line 330, in __init__
    super().__init__(coordinator, device)
  File "/config/custom_components/culligan/entity.py", line 20, in __init__
    model=f"{self.device._name + ' ' + self.device._device_model_number}",
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CulliganIoTSoftener' object has no attribute '_device_model_number'

**Comment by rewardone** [comment]
My bad on not keeping those synced.
Pushing new beta shortly with the import correct. 
Property was changed to be 'device_model_number' with no leading underscore if you wanted to adjust that on your local.

**Comment by cpettis** [comment]
That fixed it. 
I did see a couple of things, not sure how you could fix it. The salt level low shows true, even though its not. The only possibly useful property that is not listed is "days_salt_remaining". 
Thanks for updating this so quickly.
![Culligan2](https://github.com/rewardone/homeassistant-culligan-water-softener/assets/71725059/ceb55a54-cee9-445d-ab64-1b23e4b54504)
![Culligan3](https://github.com/rewardone/homeassistant-culligan-water-softener/assets/71725059/12bbed71-1d1e-4c88-8da9-03e057905aae)
![Culligan](https://github.com/rewardone/homeassistant-culligan-water-softener/assets/71725059/ef699676-5a62-4512-9c97-dc3fb1176114)

**Comment by rewardone** [comment]
I can add in days_salt_remaining. My unit reports 0 for that field, so I had not included it. 

The salt_low is hard. You can see in .const the values in ayla and approximate values in culliganiot. 
"sbt_salt_level_low"        : "salt_alarm_mode",

it is currently set to the salt_alarm_mode property. salt_level_low did not seem to exist, but you can correct me if another value should be used instead.

**Comment by rewardone** [comment]
The salt properties that are currently exposed via device properties: 

salt_level_slm_recent : 0
days_salt_remaining : 24
salt_weight_after_brine_draw : 0
manual_salt_level_rem_calc : 50
salt_type : 0
manual_salt_dosage : 71
salt_alarm_mode : 1

**Comment by cpettis** [comment]
The salt low level does seem to be difficult to pick out of the returned data. I'll let the salt level go to low on mine, and see if I can figure out the correct property for that.

The status for my system shows unavailable. For a system like mine should probably be linked to device registry json ['data']['devices']['status]['connection']['online'] value.

**Comment by rewardone** [comment]
I envision status to be 'softening', 'vacation', 'bypass', similar to the status in the app. 

The status property was not compared correctly and will be updated in the next release. 

Looking at the commands you've sent so far ... do you have the command for away mode off / vacation off? I see awayMode.set. I would have thought it would function more like bypass (bypass.on and bypass.off), but oh well. With a .set command, I would expect a property to be set. All of the request examples you sent have params{active:1}.

**Comment by cpettis** [comment]
I went back and looked at the fiddler log and corrected the json variables for the post commands. awayMode.set is a 1 or a 0 param value. the bypass.timed.on command has a duration command. 

[Post.Request.Example corrected.txt](https://github.com/rewardone/homeassistant-culligan-water-softener/files/12909970/Post.Request.Example.corrected.txt)

**Comment by cpettis** [comment]
the new version is throwing some errors, debug log file.

[home-assistant_culligan_2023-10-15T15-43-42.327Z.log](https://github.com/rewardone/homeassistant-culligan-water-softener/files/12909977/home-assistant_culligan_2023-10-15T15-43-42.327Z.log)

**Comment by cpettis** [comment]
The Errors are all gone in 1.0.3. There are no switches yet, only sensors.

**Comment by rewardone** [comment]
Glad to hear the property resolution worked. 

Correct on switches. The ayla package has commands, but the culligan package does not (yet). The switch will be created if the device class is supported. Will work on implementing commands in the culligan package.

**Comment by rewardone** [comment]
The latest culligan package (1.1.0) has support for commands. 
The latest integration should enable the vacation/away mode switch for all device classes. 

Closing this issue as the original request is beyond complete. Further issues should be opened upon their discovery.
